import { Alert, Button, Checkbox, CircularProgress, FormControlLabel, MenuItem, Paper, Stack, TextField, Typography } from '@mui/material';
import { useQuery, useQueryClient } from '@tanstack/react-query';
import { useForm } from 'react-hook-form';
import { Link, useNavigate, useParams } from 'react-router-dom';
import { useEffect, useState } from 'react';

import { ApiError, apiRequest } from '../api/api-client';
import { equipmentLabels, type Room } from '../rooms/room-types';

type Values = { name: string; floor: number; location: string; capacity: number; description: string; status: 'available' | 'unavailable'; equipment: string[] };
const codes = Object.keys(equipmentLabels);

export function AdminRoomsPage(): React.JSX.Element {
  const rooms = useQuery({ queryKey: ['rooms'], queryFn: () => apiRequest<Room[]>('/api/v1/rooms') });
  return <Stack spacing={4}><Stack direction="row" justifyContent="space-between"><div><Typography component="h1" variant="h2">Управление комнатами</Typography><Typography color="text.secondary">Создавайте и изменяйте переговорные. Удаление не поддерживается.</Typography></div><Button component={Link} to="/admin/rooms/new" variant="contained">Создать комнату</Button></Stack>{rooms.isPending ? <CircularProgress /> : null}{rooms.isError ? <Alert severity="error">Не удалось загрузить комнаты.</Alert> : null}{rooms.data?.map((room) => <Paper key={room.id} sx={{ p: 3 }}><Stack direction="row" justifyContent="space-between"><div><Typography variant="h5">{room.name}</Typography><Typography color="text.secondary">Этаж {room.floor} · {room.location} · {room.capacity} чел. · {room.status === 'available' ? 'Доступна' : 'Недоступна'}</Typography></div><Button component={Link} to={`/admin/rooms/${room.id}/edit`}>Изменить</Button></Stack></Paper>)}</Stack>;
}

export function AdminRoomFormPage(): React.JSX.Element {
  const navigate = useNavigate(); const queryClient = useQueryClient(); const { roomId } = useParams(); const id = roomId ?? ''; const editing = Boolean(roomId);
  const room = useQuery({ enabled: editing, queryKey: ['rooms', id], queryFn: () => apiRequest<Room>(`/api/v1/rooms/${encodeURIComponent(id)}`) });
  const form = useForm<Values>({ defaultValues: { name: '', location: '', description: '', status: 'available', equipment: [] } });
  useEffect(() => { if (room.data) form.reset({ name: room.data.name, floor: room.data.floor, location: room.data.location, capacity: room.data.capacity, description: room.data.description ?? '', status: room.data.status, equipment: room.data.equipment }); }, [form, room.data]);
  const [file, setFile] = useState<File>(); const [error, setError] = useState<string>();
  const submit = form.handleSubmit(async (values) => { setError(undefined); try { const result = editing ? await apiRequest<Room>(`/api/v1/rooms/${encodeURIComponent(id)}`, { method: 'PATCH', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ ...values, version: room.data!.version }) }) : await apiRequest<Room>('/api/v1/rooms', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify(values) }); let saved = result; if (file) { const data = new FormData(); data.set('image', file); data.set('version', String(result.version ?? 1)); saved = await apiRequest<Room>(`/api/v1/rooms/${encodeURIComponent(result.id)}/image`, { method: 'POST', body: data }); } await queryClient.invalidateQueries({ queryKey: ['rooms'] }); navigate(`/catalog/${saved.id}`, { state: { message: 'Комната сохранена.' } }); } catch (reason) { setError(reason instanceof ApiError ? reason.fieldErrors.join(' ') || reason.message : 'Не удалось сохранить комнату.'); } });
  if (editing && room.isPending) return <CircularProgress />;
  return <Stack component="form" onSubmit={submit} spacing={3}><Typography component="h1" variant="h2">{editing ? 'Изменение комнаты' : 'Новая комната'}</Typography>{error ? <Alert severity="error">{error}</Alert> : null}<TextField label="Название" {...form.register('name')} required /><TextField label="Этаж" type="number" {...form.register('floor', { valueAsNumber: true })} required /><TextField label="Расположение" {...form.register('location')} required /><TextField label="Вместимость" type="number" {...form.register('capacity', { valueAsNumber: true })} required /><TextField label="Описание" multiline minRows={3} {...form.register('description')} /><TextField label="Статус" select {...form.register('status')}><MenuItem value="available">Доступна</MenuItem><MenuItem value="unavailable">Недоступна — существующие встречи сохранятся</MenuItem></TextField><Typography>Оборудование</Typography>{codes.map((code) => <FormControlLabel key={code} control={<Checkbox value={code} {...form.register('equipment')} />} label={equipmentLabels[code as keyof typeof equipmentLabels]} />)}<Button component="label">{file ? file.name : 'Выбрать PNG или JPEG до 5 МиБ'}<input accept="image/png,image/jpeg" hidden onChange={(event) => setFile(event.target.files?.[0])} type="file" /></Button>{editing && room.data?.imageUrl ? <Button color="error" onClick={async () => { try { await apiRequest(`/api/v1/rooms/${id}/image`, { method: 'DELETE', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ version: room.data!.version ?? 1 }) }); await queryClient.invalidateQueries({ queryKey: ['rooms'] }); navigate(`/admin/rooms/${id}/edit`); } catch { setError('Не удалось удалить изображение.'); } }}>Удалить изображение</Button> : null}<Stack direction="row" spacing={2}><Button type="submit" variant="contained">Сохранить</Button><Button onClick={() => navigate('/admin/rooms')}>Отмена</Button></Stack></Stack>;
}
