import { Alert, Button, CircularProgress, Dialog, DialogActions, DialogContent, DialogTitle, Paper, Stack, TextField, Typography } from '@mui/material';
import { useQuery, useQueryClient } from '@tanstack/react-query';
import { useRef, useState } from 'react';
import { Link, useLocation, useParams } from 'react-router-dom';

import { ApiError, apiRequest } from '../api/api-client';
import type { BookingDetail } from '../bookings/booking-types';
import { errorMessage, isUnknownResult } from '../bookings/booking-utils';
import { useAuth } from '../auth/auth-context';

export function BookingDetailPage(): React.JSX.Element {
  const { bookingId = '' } = useParams(); const location = useLocation(); const queryClient = useQueryClient(); const { session } = useAuth();
  const [dialogOpen, setDialogOpen] = useState(false); const [cancelError, setCancelError] = useState<string>(); const [reason, setReason] = useState('');
  const cancelErrorRef = useRef<HTMLDivElement>(null);
  const booking = useQuery({ queryKey: ['bookings', bookingId], queryFn: () => apiRequest<BookingDetail>(`/api/v1/bookings/${encodeURIComponent(bookingId)}`) });
  if (booking.isPending) return <CircularProgress aria-label="Загрузка бронирования" />;
  if (booking.isError) return <Alert severity="error">{booking.error instanceof ApiError && booking.error.status === 404 ? 'Бронирование не найдено или недоступно.' : 'Не удалось загрузить бронирование.'}</Alert>;
  const value = booking.data!; const owns = value.owner.email === session!.user.email; const canEdit = value.status === 'scheduled' && !value.isCurrent && owns; const canCancel = canEdit || (session!.user.role === 'admin' && value.status === 'scheduled' && !value.isCurrent);
  const cancel = async () => { setCancelError(undefined); try { const result = await apiRequest<BookingDetail>(`/api/v1/bookings/${encodeURIComponent(bookingId)}`, { body: JSON.stringify({ version: value.version, ...(owns ? {} : { reason }) }), headers: { 'content-type': 'application/json' }, method: 'DELETE' }); queryClient.setQueryData(['bookings', bookingId], result); await queryClient.invalidateQueries({ queryKey: ['bookings'] }); await queryClient.invalidateQueries({ queryKey: ['rooms'] }); setDialogOpen(false); setReason(''); } catch (error) { setCancelError(isUnknownResult(error) ? 'Результат операции неизвестен. Обновите детали перед повтором.' : errorMessage(error)); queueMicrotask(() => cancelErrorRef.current?.focus()); } };
  const closeDialog = () => { if (reason && !window.confirm('Уйти без сохранения введённой причины отмены?')) return; setDialogOpen(false); setReason(''); setCancelError(undefined); };
  return <Stack spacing={4}><div><Typography component="h1" variant="h2">{value.subject}</Typography><Typography color="text.secondary" sx={{ mt: 1 }}>{value.room.name} · {value.date} · {value.start}–{value.end}</Typography></div>{typeof location.state === 'object' && location.state && 'message' in location.state ? <Alert severity="success">{String(location.state.message)}</Alert> : null}<Paper sx={{ p: 3 }}><Stack spacing={2}><Typography>Участников: {value.participants}</Typography><Typography>Описание: {value.description ?? 'отсутствует'}</Typography><Typography>Статус: {value.status === 'cancelled' ? 'Отменено' : value.status === 'completed' ? 'Завершено' : value.isCurrent ? 'Идёт сейчас' : 'Запланировано'}</Typography><Typography color="text.secondary">Организатор: {value.owner.name}, {value.owner.email}</Typography>{value.cancellation ? <Alert severity="info">Отменено {new Date(value.cancellation.cancelledAt).toLocaleString('ru-RU')}. {value.cancellation.type === 'owner' ? 'Встречу отменил владелец.' : `Администратор ${value.cancellation.actor.name ?? ''} отменил встречу. Причина: ${value.cancellation.reason ?? 'не указана'}`}</Alert> : null}<Stack direction="row" spacing={2}>{canEdit ? <Button component={Link} to={`/bookings/${bookingId}/edit`} variant="contained">Изменить</Button> : null}{canCancel ? <Button color="error" onClick={() => setDialogOpen(true)}>Отменить</Button> : null}<Button component={Link} to="/bookings">К списку</Button></Stack></Stack></Paper><Dialog onClose={closeDialog} open={dialogOpen}><DialogTitle>Отменить встречу?</DialogTitle><DialogContent><Typography>Будет отменена встреча «{value.subject}» в комнате {value.room.name}, {value.date} {value.start}–{value.end}.</Typography>{!owns ? <TextField autoFocus fullWidth label="Причина отмены" multiline onChange={(event) => setReason(event.target.value)} required sx={{ mt: 2 }} value={reason} /> : null}{cancelError ? <Alert ref={cancelErrorRef} severity="error" sx={{ mt: 2 }} tabIndex={-1}>{cancelError}</Alert> : null}</DialogContent><DialogActions><Button onClick={closeDialog}>Не отменять</Button><Button color="error" onClick={() => void cancel()} variant="contained">Подтвердить отмену</Button></DialogActions></Dialog></Stack>;
}
